language: python
python:
  - "3.6"

install:
  - echo "Ignoring Travis default pip install, will manually install in travis-script.sh"

before_script:
  - "pip install -r requirements.txt"
  # - bash ./scripts/run_unit_tests.sh

script:
  - bash ./travis-script.sh

after_script:
  - bash ./teardown.sh
