language: python
os:
  - linux
python:
  - "3.9"

addons:
  apt:
    packages:
      - expect-dev # for unbuffer

install:
  - echo "Starting Travis"

before_script:
  - bash ./run_unit_tests.sh

script:
  - unbuffer bash ./publish.sh

