[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "car-connector-framework"
description = "CAR service connector framework"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"

authors = [
    { name = "IBM", email = "noreply@ibm.com" }
]

urls = { "Homepage" = "https://github.com/IBM/cp4s-car-connector-framework" }

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests>=2.32.4,<3",
    "python-json-logger>=4.0.0,<5",
    "jschon>=0.11.1,<1",
    "jwcrypto>=1.5.6,<2",
    "urllib3>=2.6.3,<3"
]

dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "car_framework.__version__"}

[tool.setuptools.packages.find]
exclude = ["tests"]