name: Unit test and Publish
on:
  push:
    branches: '**'
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: sudo apt-get install -y expect-dev
    - name: Run unit test
      run: bash ./run_unit_tests.sh
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Publish
      env:
        PYPI_API_REPOSITORY_PROD: 'https://upload.pypi.org/legacy/'
        PYPI_API_TOKEN_PROD: ${{ secrets.PYPI_API_TOKEN_PROD }}
        PYPI_API_REPOSITORY_TEST: 'https://test.pypi.org/legacy/'
        PYPI_API_TOKEN_TEST: ${{ secrets.PYPI_API_TOKEN_TEST }}
        EFFECTIVE_BRANCH: ${{ github.head_ref || github.ref_name }}
        RUN_NUMBER: ${{ github.GITHUB_RUN_NUMBER }}
        VERSION_LAST_TAG: ${{ steps.previoustag.outputs.tag }}
      run: unbuffer bash ./publish.sh

